name: MacOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    env:
      CMAKE_BUILD_TYPE: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@v3.29.2

      - name: Set up Homebrew cache
        uses: actions/cache@v4
        with:
          path: |
            /Users/runner/Library/Caches/Homebrew
            /usr/local/Homebrew/Library/Taps
            /usr/local/Cellar
          key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}
          restore-keys: |
            ${{ runner.os }}-brew-

      - name: Install dependencies
        run: |
          brew update
          brew install openssl opencv libpcap cmake git pcapplusplus

      - name: Configure and Build
        run: |
          cd heiFIP/

          mkdir -p build && cd build

          cmake .. \
            -DCMAKE_BUILD_TYPE=Release
          
          make
