name: MacOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    env:
      CMAKE_BUILD_TYPE: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@v3.29.2

      - name: Install dependencies (macOS)
        run: |
          brew update
          brew install openssl opencv libpcap cmake git pcapplusplus

      - name: Configure and Build (macOS)
        run: |
          cd heiFIP/

          # Create build directory
          mkdir -p build && cd build

          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_MANUAL_PCAPPLUSPLUS=ON \
            -DPcapPlusPlus_INCLUDE_DIRS="/opt/homebrew/Cellar/pcapplusplus/25.05/include" \
            -DPcapPlusPlus_LIBRARIES="/opt/homebrew/Cellar/pcapplusplus/25.05/lib/libCommon++.a;/opt/homebrew/Cellar/pcapplusplus/25.05/lib/libPacket++.a;/opt/homebrew/Cellar/pcapplusplus/25.05/lib/libPcap++.a" \
            -DUSE_MANUAL_OPENSSL=ON \
            -DOPENSSL_INCLUDE_DIR="/opt/homebrew/opt/openssl@3/include" \
            -DOPENSSL_CRYPTO_LIBRARY="/opt/homebrew/opt/openssl@3/lib/libcrypto.a"
          
          make
